services:
  app:
    build: .
    container_name: movie-list-app
    depends_on:
      - postgres
    ports:
      - "6060:8080"

  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "6543:5432"