services:
  postgres:
    container_name: database
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: ./pg_data:/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"